apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-ultra
  namespace: crud-ultra
spec:
  ingressClassName: nginx
  rules:
    - host: crud-ultra.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crud-ultra
                port:
                  number: 80
